# UCAD example API test http request

### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJ1c2VybmFtZSI6Im1hdHRpIiwiZW1haWwiOiJtYXR0aUBleGFtcGxlLmNvbSIsInVzZXJfbGV2ZWxfaWQiOjEsImNyZWF0ZWRfYXQiOiIyMDI1LTExLTE3VDEyOjE1OjA3LjAwMFoiLCJpYXQiOjE3NjMzODQ0NjEsImV4cCI6MTc2MzQ3MDg2MX0.Vt3N-fryyzAvUo3cOlbXAWNvfoim9d6-GHQe767a03g


### Note: Install VSCode REST Client extension to use this file

### GET server root
GET http://localhost:3000/


## /media resource

### GET /media
GET http://localhost:3000/api/media
Authorization: Bearer {{token}}

### GET media items by user (logged in)
GET http://localhost:3000/api/media/user
Authorization: Bearer {{token}}

### Add new media item including media file
POST http://localhost:3000/api/media
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="user_id"

2
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./test-cat.png
------Boundary--

### Update existing media item
PUT http://localhost:3000/api/media/4
Authorization: Bearer {{token}}
content-type: application/json

{
  "title": "New title",
  "description": "Updated desc"
}

### Delete existing media item
DELETE http://localhost:3000/api/media/2
Authorization: Bearer {{token}}



######################



## /users resource

### GET /users
GET http://localhost:3000/api/users
Authorization: Bearer {{token}}

### GET user by id
GET http://localhost:3000/api/users/6
Authorization: Bearer {{token}}

### Add new user
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "testimies",
  "password": "miesmies",
  "email": "olen.mies@mailmail.com"
}

### Login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "JohnDoe",
  "password": "to-be-hashed-pw1"
}

### Auth GET me
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{token}}

### Update existing user
PUT http://localhost:3000/api/users/2
Authorization: Bearer {{token}}
content-type: application/json

{
  "username": "testinainen",
  "password": "nainennainen",
  "email": "olen.nainen@mailmail.com"
}

### Delete existing user
DELETE http://localhost:3000/api/users/5
Authorization: Bearer {{token}}


######################


### GET /likes
GET http://localhost:3000/api/likes

### GET likes user by id
GET http://localhost:3000/api/likes/2

### Add new like
POST http://localhost:3000/api/likes
content-type: application/json

{
  "media_id": 1,
  "user_id": 4
}

### Delete existing like
DELETE http://localhost:3000/api/likes/3